
name : pr

on :
  pull_request :
    branches : [ master ]

jobs :

  job_context_test :
    uses : getbento/wretry.action/.github/workflows/JobContextActionTest.yml@master

  matrix_context_test :
    uses : getbento/wretry.action/.github/workflows/MatrixContextActionTest.yml@master
